import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { PGlite } from '@electric-sql/pglite';
const uid='11111111-1111-4111-8111-111111111111', other='22222222-2222-4222-8222-222222222222';
const migration=readFileSync(new URL('../../supabase/migrations/20260918120432_finance_assistant.sql',import.meta.url),'utf8');
const integrity=readFileSync(new URL('../../supabase/migrations/20260924120000_finance_integrity_foundation.sql',import.meta.url),'utf8');
test('fila, isolamento, confirmação e efeitos financeiros atômicos em PostgreSQL',async()=>{
 const db=new PGlite();
 try {
 await db.exec(`create role anon;create role authenticated;create role service_role;
 create table finance_users(id uuid primary key);insert into finance_users values('${uid}'),('${other}');
 create table dashboard_accounts(id uuid primary key,finance_user_id uuid,active boolean);
 create table finance_transactions(id uuid primary key default gen_random_uuid(),user_id uuid,telegram_message_id bigint,transaction_type text,amount numeric,category text,description text,transaction_date date,created_at timestamptz default now(),deleted_at timestamptz,updated_by_account_id uuid,deleted_by_account_id uuid);`);
 await db.exec(migration);
 await db.exec(integrity);
 const scalar=async(sql,values=[]) => (await db.query(sql,values)).rows[0].v;
 const enqueue=(key,payload={},user=uid)=>scalar("select finance_assistant_enqueue($1,null,'dashboard',$2,$3::jsonb) v",[user,key,JSON.stringify(payload)]);
 const claim=()=>scalar('select finance_assistant_claim() v');
 const finish=(j,op)=>scalar("select finance_assistant_finish($1,$2,$3::jsonb,'proposed') v",[j.id,j.lease_token,JSON.stringify(op)]);
 const count=()=>scalar('select count(*)::int v from finance_transactions where deleted_at is null');
 const tx={transaction_type:'despesa',amount:45,description:'Almoço',category:'Alimentação',transaction_date:'2020-01-01'};
 const first=await enqueue('one');assert.equal((await enqueue('one')).id,first.id);
 const claimed=await claim();await enqueue('two');assert.equal(await claim(),null,'same wallet cannot process concurrently');
 const made=await finish(claimed,{action:'create',transactions:[tx]});assert.equal(await count(),1);
 await finish(claimed,{action:'create',transactions:[tx]});assert.equal(await count(),1,'repeat finish does not duplicate');
 const second=await claim();const duplicate=await finish(second,{action:'create',transactions:[tx]});assert.equal(duplicate.status,'awaiting_confirmation');assert.equal(await count(),1);
 await enqueue('foreign-confirm',{action:'confirm',confirmation_id:duplicate.id},other);await finish(await claim(),{action:'chat'});assert.equal(await count(),1);
 await enqueue('confirm',{action:'confirm',confirmation_id:duplicate.id});await finish(await claim(),{action:'chat'});assert.equal(await count(),2);
 await enqueue('reconfirm',{action:'confirm',confirmation_id:duplicate.id});await finish(await claim(),{action:'chat'});assert.equal(await count(),2);
 const tid=made.result.transactions[0].id;
 await enqueue('foreign-delete',{},other);await assert.rejects(finish(await claim(),{action:'delete',target_id:tid}));
 await db.exec("update finance_assistant_jobs set status='failed' where request_key='foreign-delete'");
 await enqueue('delete');const pending=await finish(await claim(),{action:'delete',target_id:tid});assert.equal(pending.status,'awaiting_confirmation');assert.equal(await count(),2);
 await enqueue('cancel',{action:'cancel',confirmation_id:pending.id});await finish(await claim(),{action:'chat'});assert.equal(await count(),2);
 await enqueue('batch');const batch=await finish(await claim(),{action:'create',transactions:[tx,{...tx,amount:50}]});assert.equal(batch.status,'awaiting_confirmation');assert.equal(await count(),2);
 await enqueue('batch-confirm',{action:'confirm',confirmation_id:batch.id});await finish(await claim(),{action:'chat'});assert.equal(await count(),4);
 await enqueue('invalid');const invalid=await claim();await assert.rejects(finish(invalid,{action:'create',transactions:[{...tx,amount:-1}]}));assert.equal(await count(),4);
 await db.exec('set role anon');await assert.rejects(db.query('select * from finance_assistant_jobs'));await assert.rejects(db.query('select finance_assistant_claim()'));
 }finally{await db.close()}
});
