-- Soft deletion keeps transactions recoverable without changing their identity.
alter table public.finance_transactions
  add column if not exists deleted_at timestamptz;

create index if not exists finance_transactions_active_user_date_idx
  on public.finance_transactions (user_id, transaction_date desc, id desc)
  where deleted_at is null;

create index if not exists finance_transactions_trash_deleted_at_idx
  on public.finance_transactions (deleted_at)
  where deleted_at is not null;

-- Minimal tombstones keep old Telegram updates idempotent after physical purging.
-- Negative message IDs are generated by the dashboard and are not Telegram updates.
create table if not exists public.finance_transaction_tombstones (
  user_id uuid not null references public.finance_users(id) on delete cascade,
  telegram_message_id bigint not null,
  primary key (user_id, telegram_message_id),
  constraint finance_transaction_tombstones_telegram_id_check
    check (telegram_message_id > 0)
);

alter table public.finance_transaction_tombstones enable row level security;
revoke all on table public.finance_transaction_tombstones from public, anon, authenticated;
grant select, insert on table public.finance_transaction_tombstones to service_role;

create or replace function public.finance_reject_purged_telegram_update()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if new.telegram_message_id > 0 and exists (
    select 1
    from public.finance_transaction_tombstones as tombstone
    where tombstone.user_id = new.user_id
      and tombstone.telegram_message_id = new.telegram_message_id
  ) then
    raise unique_violation using
      message = 'Telegram message already processed',
      constraint = 'finance_transaction_tombstones_pkey';
  end if;
  return new;
end;
$$;

create or replace function public.finance_preserve_deleted_telegram_update()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if old.telegram_message_id > 0 then
    insert into public.finance_transaction_tombstones (user_id, telegram_message_id)
    values (old.user_id, old.telegram_message_id)
    on conflict do nothing;
  end if;
  return old;
end;
$$;

revoke all on function public.finance_reject_purged_telegram_update() from public, anon, authenticated;
revoke all on function public.finance_preserve_deleted_telegram_update() from public, anon, authenticated;

drop trigger if exists finance_reject_purged_telegram_update on public.finance_transactions;
create trigger finance_reject_purged_telegram_update
  before insert on public.finance_transactions
  for each row execute function public.finance_reject_purged_telegram_update();

drop trigger if exists finance_preserve_deleted_telegram_update on public.finance_transactions;
create trigger finance_preserve_deleted_telegram_update
  after delete on public.finance_transactions
  for each row execute function public.finance_preserve_deleted_telegram_update();
